### ISSUE TITLE
Admin Panel - Refonte

### ISSUE THREAD

**Issue by yyewolf** [yyewolf/bar#40]
**Features** :

- [ ] Faire le système de modules (et sous-modules)
- [ ] Modules : Remettre les actuels (bas niveau) 
- [ ] Module : Gestion des stocks
- [ ] Module : Utilisateurs qui veulent staff
- [ ] Module : Detection d'incohérences https://github.com/yyewolf/bar/issues/24
- [ ] Module : Créditer un compte https://github.com/yyewolf/bar/issues/23
- [ ] Module : Solder un compte https://github.com/yyewolf/bar/issues/22
- [ ] Module : Tracking des recharges https://github.com/yyewolf/bar/issues/21
- [ ] Module : Ajout de produit simple https://github.com/yyewolf/bar/issues/25
- [ ] Module : Stats https://github.com/yyewolf/bar/issues/29
- [ ] Module : Lecture de bug report https://github.com/yyewolf/bar/issues/30
- [ ] Module : Modification de compte simplifier avec scan ou barre de recherche
